### ISSUE TITLE
Complete payload in logs

### ISSUE THREAD

**Issue by raphaelguye** [Tealium/tealium-ios#108]
When calling a tracking method in dev, only a part of the payload is logged.

I would like to get the full payload. Is it possible ?

**Comment by craigrouse** [comment]
@ragu89 Which parts of the payload are missing? I've just tested, and we usually log the whole payload. Which log level are you using?

**Comment by raphaelguye** [comment]
I only have the first 24 lines of the payload. ordered by property name.

This is the kind of log I get everytime I call a method from the SDK :
```
TEALIUM iOS 5.5.1: x.x.x: Sent dispatch.
 datasources payload: {ect x.x.x: Dispatch: 
"app_name" = appname;
"app_rdns" = "x.x.x";
"app_uuid" = "11111-154F-4BC7-9E56-2222222222";
"app_version" = "0.5.2";
autotracked = true;
"call_type" = link;
carrier = Carrier;
"connection_type" = wifi;
device = "iPhone10,4";
"device_architecture" = 64;
"device_battery_percent" = 100;
"device_cputype" = ARM64;
"device_ischarging" = false;
"device_language" = "en-CH";
"device_orientation" = Portrait;
"device_os_version" = "12.3.1";
"device_resolution" = 750x1334;
"library_version" = "5.5.1";
"lifecycle_dayofweek_local" = 2;
"lifecycle_dayssincelastwake" = 0;
"lifecycle_dayssincelaunch" = 0;
"lifecycle_firstlaunchdate" = "2019-07-15T12:59:35Z";
"lifecycle_firstlaunchdate_MMDDYYYY" = "07/15/2019";
"lifecycle_hourofday_local" = 16;
```

**Comment by christinasund** [comment]
@ragu89 Are you able to see all of the data in live events or your analytics vendor's dashboard?

**Comment by raphaelguye** [comment]
In fact no, that's why I would need the payload.

For the views tracking and the events tracking everything is working fine, we can see the results in our vendor's dashboard.
But for the lifecycle (launch, sleep, wake), we haven't the informations.

**Comment by craigrouse** [comment]
@ragu89 Could you please email the support team (support at tealium dot com), and we'll get you some personalised support, and if necessary, arrange a screen share with you. Thank you.

**Comment by raphaelguye** [comment]
ok I will, thank you
