### ISSUE TITLE
Requires very old version of Xcode

### ISSUE THREAD

**Issue by adamlatitude** [Tealium/tealium-ios#115]
Please update this code. Xcode 11 is out in GM, Xcode 10.3 is the current version, I have to go and download Xcode 10.1 before I can even open these sample projects!

**Comment by craigrouse** [comment]
@adamlatitude apologies for this. I think this PR will help you: https://github.com/Tealium/tealium-ios/pull/106

It's an oversight that we haven't merged this yet. We will get it merged ASAP. Let me know if this helps you. Thanks for taking the time to report this.

**Comment by craigrouse** [comment]
@adamlatitude closing this since we've now merged the pull request. Thanks for keeping us on our toes. Let us know if we can be of further assistance.
