### ISSUE TITLE
UIWebView and Apple review

### ISSUE THREAD

**Issue by JuhaO81** [Tealium/tealium-ios#116]
**ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs.**

We and I believe many other apps have gotten above warning from Apple review lately. UIWebView is still present in iOS13 and it works so far but Apple is not maintaining it any more. Also at some point they will start rejecting apps using it. 

What is your plan and timetable with UIWebView removal? All references to it need to be removed if I understood this correctly.

**Comment by craigrouse** [comment]
@JuhaO81 The default implementation is now WKWebView, but we still have UIWebView available for backwards compatibility. At present, I know Xcode will throw a warning if you have UIWebView in your app, but it doesn't stop you from building. With Catalyst, however, I believe it does create a problem, as UIKit for Mac does not include UIWebView at all.

We don't have a defined timeline yet, but we do plan to remove UIWebView soon to ensure you don't get any build issues. I will leave this issue open and post back when we have an update for you.

**Comment by JuhaO81** [comment]
This is not just build issue. Apple says: We will stop accepting apps using UIWebView into App Store. They don't say when. Please prioritise this work. I can see some major players like Google already removed UIWebView from firebase: https://firebase.google.com/support/release-notes/ios

**Comment by m1entus** [comment]
Same here, we have issue with submitting, please remove UIWebView :

`Dear Developer,

We identified one or more issues with a recent delivery for your app, 1.0.0 (20191003.6). Your delivery was successful, but you may wish to correct the following issues in your next delivery:

ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

After you’ve corrected the issues, you can use Xcode or Application Loader to upload a new binary to App Store Connect.

Best regards,

The App Store Team`

**Comment by m1entus** [comment]
@craigrouse btw. what backwards compatibility ? WKWebView is available since iOS 8 and TealiumIOS based on podfile also is available from iOS8. So UIWebView should be removed to be able to submit app.

**Comment by craigrouse** [comment]
@m1entus Thanks for confirming. We will prioritize this.

There were numerous issues with WKWebView, some of which were only fixed as late as iOS11, unfortunately. Our SDK therefore defaults to UIWebView prior to iOS 11. 

We'll circle back on this very soon.

**Comment by JuhaO81** [comment]
Personally I don't see why the library needs to have webview at all. It is native client sending data to service.

**Comment by craigrouse** [comment]
@JuhaO81 The webview is only required for Tealium iQ, which allows you to use our existing library of JavaScript tags to send data to vendors. If you'd prefer to avoid the webview, you can use our EventStream solution, which is 100% server-side.

**Comment by JuhaO81** [comment]
Thanks for info!

**Comment by christinasund** [comment]
@JuhaO81 and @m1entus We have just released a new version that does not have any instances of UIWebView: https://github.com/Tealium/tealium-ios/releases/tag/5.6.0

Thanks!

**Comment by JuhaO81** [comment]
Nice! I will update immediately!
