### ISSUE TITLE
Long console logs are cut

### ISSUE THREAD

**Issue by JuhaO81** [Tealium/tealium-ios#117]
When I run our app in simulator I can see full tealium logs in Xcode but when running the app on device  without debug mode I need to use console.app to see the logs. Long logs are cut there. 

**Steps**
- Install the app to device (not in debug mode). 
- Connect iPhone to mac via USB and open console.app on mac
- Open app and perform some use cases producing Tealium events
- Verify from logs correct events are sent

**Actual result** 
Testers are unable to verify Tealium events as they are cut. 

**Expected result**
Full logs are available 

More info of the issue here and some fix proposals as well
https://stackoverflow.com/questions/39584707/nslog-on-devices-in-ios-10-xcode-8-seems-to-truncate-why

**Comment by christinasund** [comment]
@JuhaO81 I tried to repro but I don't think my payload was large enough to see what you were seeing. Is there any way you could send a .swift/.m file with just the payload dictionary you are sending in the track call? 

Also, another question would be: Are you seeing all of the data make it downstream? Is the only problem  that you can't see the payload in the console log?

**Comment by JuhaO81** [comment]
> @JuhaO81 I tried to repro but I don't think my payload was large enough to see what you were seeing. Is there any way you could send a .swift/.m file with just the payload dictionary you are sending in the track call?

Could you provide me your company email so I can send some example logs for you.

> Also, another question would be: Are you seeing all of the data make it downstream? Is the only problem that you can't see the payload in the console log?

To answer this I need the working logs :) Our project is huge and we need to be able to verify the Tealium events "on fly". Generating set of events now and trying to verify them few hours later from Adobe UI is really not working us. Too many test users and too much data.

**Comment by christinasund** [comment]
@JuhaO81 Ah, that makes sense. You can send those logs to: support@tealium.com. Thank you!

**Comment by christinasund** [comment]
@JuhaO81 Closing this issue for now. Keep an eye out for version 2.0.0 of our [Swift library](https://docs.tealium.com/platforms/ios-swift/) coming out soon. This release includes a feature that allows you to use `OSLog` instead of `print` if you wish 😁
