### ISSUE TITLE
Duplicated params tracked device_ischarging and device_is_charging

### ISSUE THREAD

**Issue by opolstianko** [Tealium/tealium-ios#125]
Hello, we have noticed there are duplicated params with different names but same meaning:
device_ischarging and device_is_charging

Is that known issue?

**Comment by craigrouse** [comment]
@opolstianko Yes, we're aware, and this is not an issue. At some point in the past, we migrated to the new name, but we had to keep the old name to avoid breaking existing configurations. It's safe to use either variable. Thanks for reporting it in any case.
