### ISSUE TITLE
TealiumIOS: +[TEALDeviceDataSources model:] 

### ISSUE THREAD

**Issue by chibombo** [Tealium/tealium-ios#128]
Actually my app crash using Tealium 5.6.0

> OS Version:          iPhone OS 13.4.1 (17E8258)
Release Type:        User
Baseband Version:    1.05.28
Report Version:      104

> Exception Type:  EXC_CRASH (SIGABRT)
> Exception Codes: 0x0000000000000000, 0x0000000000000000
> Exception Note:  EXC_CORPSE_NOTIFY
> Triggered by Thread:  3

> Last Exception Backtrace:
> 0   CoreFoundation                	0x1960a0374 __exceptionPreprocess + 228 (NSException.m:199)
> 1   libobjc.A.dylib               	0x195db4c1c objc_exception_throw + 60 (objc-exception.mm:565)
> 2   CoreFoundation                	0x1960f95b8 _CFThrowFormattedException + 116 (CFObject.m:1994)
> 3   CoreFoundation                	0x196103530 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:].cold.4 + 52
> 4   CoreFoundation                	0x195f871e0 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:] + 260 (NSPlaceholderDictionary.m:0)
> 5   CoreFoundation                	0x195f78a1c +[NSDictionary dictionaryWithObjects:forKeys:count:] + 60 (NSDictionary.m:604)
> 6   TealiumIOS                    	0x101eb646c +[TEALDeviceDataSources model:] + 400 (TEALDeviceDataSources.m:188)
> 7   TealiumIOS                    	0x101eb5b10 -[TEALDeviceDataSources backgroundDataSources] + 140 (TEALDeviceDataSources.m:63)
> 8   TealiumIOS                    	0x101e976f4 -[TEALDataSources backgroundSafeDataSources:] + 296 (TEALDataSources.m:94)
> 9   TealiumIOS                    	0x101e9ee00 __50-[Tealium trackType:title:dataSources:completion:]_block_invoke + 112 (Tealium.m:185)
> 10  libdispatch.dylib             	0x195d3eec4 _dispatch_call_block_and_release + 32 (init.c:1408)
> 11  libdispatch.dylib             	0x195d4033c _dispatch_client_callout + 20 (object.m:495)
> 12  libdispatch.dylib             	0x195d4685c _dispatch_lane_serial_drain + 568 (inline_internal.h:2484)
> 13  libdispatch.dylib             	0x195d47290 _dispatch_lane_invoke + 400 (queue.c:3863)
> 14  libdispatch.dylib             	0x195d50928 _dispatch_workloop_worker_thread + 584 (queue.c:6445)
> 15  libsystem_pthread.dylib       	0x195da7714 _pthread_wqthread + 276 (pthread.c:2351)
> 16  libsystem_pthread.dylib       	0x195dad9c8 start_wqthread + 8

**Comment by christinasund** [comment]
@chibombo Thanks for bringing this to our attention, we will look into it

**Comment by christinasund** [comment]
hi @chibombo Sorry I didn't notice this initially, but it looks like this was fixed in a more recent version. Check out version [5.6.2](https://github.com/Tealium/tealium-ios/releases/tag/5.6.2). Let us know if updating resolves the problem, thanks!
