### ISSUE TITLE
Minimum deployment target for v5.0.0 or higher if possible

### ISSUE THREAD

**Issue by FBente** [Tealium/tealium-ios#13]
The iOS version in the [Info.plist](https://github.com/Tealium/tealium-ios/blob/v5.0.0/TealiumIOS.framework/Info.plist) of [v5.0.0](https://github.com/Tealium/tealium-ios/tree/v5.0.0) is set to iOS 8.0.
It would be very nice if it is possible to set the [podspec.json](https://github.com/CocoaPods/Specs/blob/master/Specs/TealiumIOS/5.0.0/TealiumIOS.podspec.json) version to iOS 8.0 too to use `pod 'TealiumIOS', '<= 5.0.0'` for podfiles with `platform :ios, '8.0'`.

**Comment by jalakoo** [comment]
@FBente Great recommendation, we'll look into this when we update our podspec next.

**Comment by fjtrujy** [comment]
I think that you can close this issue, if you see the last version of the pod is compatible with iOS 8.

Thanks

**Comment by FBente** [comment]
@fjtrujy Thanks! You are right. The [latest pod version](https://github.com/CocoaPods/Specs/blob/master/Specs/TealiumIOS/5.0.4/TealiumIOS.podspec.json#L22) is now compatible with iOS 8.0.
