### ISSUE TITLE
Differences between repository podspec and cocoapod podspec

### ISSUE THREAD

**Issue by fjtrujy** [Tealium/tealium-ios#14]
Hello,

If you see, your podspec
`https://github.com/Tealium/tealium-podspecs/blob/master/tealium-ios-podspec/TealiumIOS.podspec`
contains:
`s.source           = { :git => "https://github.com/tealium/tealium-ios.git", :commit => '0e45406d9cdb82ebe8e9941371e57419130577dc', :tag => 'v5.0.3' }`

But the podspec that Cocoapods has:
`https://github.com/CocoaPods/Specs/blob/master/Specs/TealiumIOS/5.0.3/TealiumIOS.podspec.json`
contains:
`"source": {
    "git": "https://github.com/tealium/tealium-ios.git",
    "commit": "42cd3ee45953cf618104f3de5dd66e5db3cdfdd6",
    "tag": "v5.0.3"
  },`

The commit is different in the podspec files. 
`0e45406d9cdb82ebe8e9941371e57419130577dc` and `42cd3ee45953cf618104f3de5dd66e5db3cdfdd6`
Probably this is due because you submitted (`pod trunk push NAME.podspec`) and then later you changed again you podspec file.

One advice here is just to specify in the podspec file the tag. If you specify tag and commit Cocoapod give more priority to the commit. For this reason when I'm executing `pod install` or `pod update` we are downloading the commit `42cd3ee45953cf618104f3de5dd66e5db3cdfdd6`

Usually the podspec file has a configuration like this one:

`s.source           = { :git => "https://github.com/fjtrujy/FTMTableSectionModules.git", :tag => s.version.to_s }` 

where previously you have defined the s.version

`s.version          = "0.1.2"`

With this approach you will avoid this kind of confusions. And you won't need to execute again the command to submit to cocoapods.

Lastly, I'm guessing that the commit that we donwload from Cocoapods doesn't contains all the fixes done in 5.0.3 because I'm still having the crash related to:
 `Protections added to the collectDispatchURL that may have caused crashes at launch time`

if you want I can create the Pull Request to update the configuration of the podspec file in the repository `https://github.com/Tealium/tealium-podspecs`

Hoping for a great response,
Francisco Javier

**Comment by jalakoo** [comment]
@fjtrujy Hey Francisco, great advice here. We've actually just released 5.0.4 which has a better fix for the collectDispatchURL bug.  If you make a pull request for the new version, that would be great!

**Comment by fjtrujy** [comment]
Thanks for your quick response.

2 Things:
- To use in the podspec file `tag => s.version.to_s`, the tag version must be `5.0.4` and right now you are using `v5.0.4`. Following the git flow this is not the proper way to name the version of the app. So, please can you rename the tag and change to `5.0.4`?
- I saw that there is already one issue regarding to put the minimum version as `8.0` I can do it as well, are you agree?

Thanks in advance,
Francisco Javier

**Comment by jalakoo** [comment]
@fjtrujy Agree. v5.x version tags have been renamed to the recommended 5.x pattern.

Thanks Francisco

**Comment by fjtrujy** [comment]
Welcome!!!
