### ISSUE TITLE
Migration to Tealium-Swift

### ISSUE THREAD

**Issue by salvatoreboemia** [Tealium/tealium-ios#147]
Hi 

I need some support in order to migrate to new SDK

in particular for this methods

- TEALConfiguration -> TealiumConfiguration
- Tealium.destroyInstance(forKey: config.instanceID()) -> ???
- trackView -> ???
- Tealium -> TealiumIstance (?)
- Tealium.newInstance -> ???
- trackEvent -> ???

Thanks

**Comment by Enricoza** [comment]
Hi @salvatoreboemia, here is the documentation about those methods:

- [TealiumConfiguration](https://docs.tealium.com/platforms/ios-swift/api/tealium-config)
- [Remove Instance](https://docs.tealium.com/platforms/ios-swift/api/tealium-instance-manager/#removeinstanceforkey)
- [Tealium constructor](https://docs.tealium.com/platforms/ios-swift/api/tealium/#tealium)
- [Track View and Event](https://docs.tealium.com/platforms/ios-swift/api/tealium/#track)

Let us know if you need anything else.

**Comment by salvatoreboemia** [comment]
> Hi @salvatoreboemia, here is the documentation about those methods:
> 
>     * [TealiumConfiguration](https://docs.tealium.com/platforms/ios-swift/api/tealium-config)
> 
>     * [Remove Instance](https://docs.tealium.com/platforms/ios-swift/api/tealium-instance-manager/#removeinstanceforkey)
> 
>     * [Tealium constructor](https://docs.tealium.com/platforms/ios-swift/api/tealium/#tealium)
> 
>     * [Track View and Event](https://docs.tealium.com/platforms/ios-swift/api/tealium/#track)
> 
> 
> Let us know if you need anything else.

thanks for your quick reply

basically 

`Tealium` has been replaced by `TealiumInstanceManager`
TealiumConfiguration.instanceID() -> ???

right?

**Comment by Enricoza** [comment]
No, `Tealium` still handles everything, the `TealiumInstanceManager` is just a utility class that handles the life span of the tealium instances in your app. 
You basically only need to use `TealiumInstanceManager` in case you want to destroy a Tealium instance.

**Comment by Enricoza** [comment]
I'm going to close this for now but feel free to re-open or open a new issue on the [Swift](https://github.com/Tealium/tealium-swift) library if you have any problems integrating it.
