### ISSUE TITLE
Carthage support?

### ISSUE THREAD

**Issue by nadav96** [Tealium/tealium-ios#15]
Hey, can you please add Carthage support? As it very inconvenient to add the framework manually on each update.

`Dependency "tealium-ios" has no shared framework schemes for any of the platforms: iOS`

Thanks.

**Comment by jalakoo** [comment]
@nadav96 We have so far been unable to make the framework compatible with Carthage (even with shared schemes enabled and that fact that we are using Carthage for part of our build process).  When either Carthage or we release a next update, we will attempt again.  Apologies for the inconvenience.

**Comment by cenbreathnach** [comment]
Hi is there any update on Carthage support?

**Comment by craigrouse** [comment]
@donedeal-cen we've discussed this recently internally, and hope to be able to support it soon. I'll post back here when we have an update.
