### ISSUE TITLE
Test Issue

### ISSUE THREAD

**Issue by simonbrowning** [Tealium/tealium-ios#153]
This is a test issue to check the configuration with the Tealium support portal.

**Comment by tealiumsupport** [comment]
test response          
                           
                            On
                            Fri, 18 Oct at  2:23 PM
                            ,  Tealium/tealium-ios ***@***.***>  wrote:
                             
 This is a test issue to check the configuration with the Tealium support portal.

**Comment by simonbrowning** [comment]
Hi yes please advise.

**Comment by simonbrowning** [comment]
Closing
