### ISSUE TITLE
Add TealiumIOSLifecycle to Cocoapods

### ISSUE THREAD

**Issue by JALsnipe** [Tealium/tealium-ios#17]
Would it be possible to also add the TealiumIOSLifecycle.framework to the podspec so I could install both TealiumIOS and the lifecycle framework through Cocoapods?

**Comment by mertid** [comment]
@JALsnipe we will have a lifecycle pod available by early next week.

**Comment by JALsnipe** [comment]
Hi @mertid, any update on this?

**Comment by mertid** [comment]
@JALsnipe Yes it is up and running on cocoapods, 
add `pod TealiumIOSLifecycle`  to your podfile and you should be good to go
