### ISSUE TITLE
Device only builds still have underscores internally

### ISSUE THREAD

**Issue by grahampett** [Tealium/tealium-ios#22]
The device only builds were recently updated to remove underscores, but they appear to have just had the .framework package file renamed. Internally, the executable file still contains underscores and in the info.plist file there are still underscores in the bundle name and bundle identifier. This has caused linking issues for us (using Xamarin - it doesn't seem to like the executable name being different from the framework package name) and iTunes is rejecting our app because of the underscore in the bundle name.

**Comment by mertid** [comment]
Hi @grahampett. This fix has been made in our 5.1 release. We plan to release it next week. Please let us know if you are still having issues after updating.

**Comment by quantumarun** [comment]
@mertid When is 5.1 release expected to be out?

**Comment by mertid** [comment]
@quantumarun 5.1   is going through QA currently. Hopefully we will release by end of week pending no issues.

**Comment by mertid** [comment]
5.1 is released
