### ISSUE TITLE
Concurrent modification crash

### ISSUE THREAD

**Issue by eriksundin** [Tealium/tealium-ios#27]
Hi, we are experiencing a crash quite frequently after upgrading to 5.1.1. We are however stepping up from the 4.x version so this issue might not be something only in 5.1.1.

Looks like some concurrent modification issue. Is there a possibility that our code could be causing it or can you see how this could be caused in the framework code?

Thanks,
Erik 

```
*** Collection <__NSArrayM: 0x1265f7070> was mutated while being enumerated.
-[TEALDispatchManager saveDispatches:completion:]

Fatal Exception: NSGenericException
0  CoreFoundation                 0x182566db0 __exceptionPreprocess
1  libobjc.A.dylib                0x181bcbf80 objc_exception_throw
2  CoreFoundation                 0x1825667e4 -[NSException name]
3  TealiumIOS                     0x101aebbb0 -[TEALDispatchManager saveDispatches:completion:] (TEALDispatchManager.m:285)
4  TealiumIOS                     0x101aeba78 -[TEALDispatchManager runDispatches:reportLast:] (TEALDispatchManager.m:271)
5  TealiumIOS                     0x101aeb070 -[TEALDispatchManager runQueuedDispatches] (TEALDispatchManager.m:137)
6  TealiumIOS                     0x101ae0040 -[Tealium(TagManagement) tagDispatchServiceWebViewReady:] (Tealium+TagManagement.m:350)
7  TealiumIOS                     0x101aefe70 __47-[TEALTagDispatchService webViewDidFinishLoad:]_block_invoke (TEALTagDispatchService.m:160)
8  libdispatch.dylib              0x181fb14bc _dispatch_call_block_and_release
9  libdispatch.dylib              0x181fb147c _dispatch_client_callout
10 libdispatch.dylib              0x181fb6b84 _dispatch_main_queue_callback_4CF
11 CoreFoundation                 0x18251cd50 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
12 CoreFoundation                 0x18251abb8 __CFRunLoopRun
13 CoreFoundation                 0x182444c50 CFRunLoopRunSpecific
14 GraphicsServices               0x183d2c088 GSEventRunModal
15 UIKit                          0x18772e088 UIApplicationMain
16 Blocket                        0x100231eb0 main (main.m:31)
17 libdispatch.dylib              0x181fe28b8 (Missing)
```

**Comment by mertid** [comment]
Hi Erik, I will delve into this today and report back to you.

**Comment by eriksundin** [comment]
Thanks @mertid , any findings on your side so far?

**Comment by mertid** [comment]
Nothing so far. Do you know how your network setting were at the time of the crash?

**Comment by eriksundin** [comment]
Like network connection you mean?
Not sure, we are collecting these crashes through Fabric from our app users. I haven't been able to reproduce it locally just yet, but we're seeing about a 1000 of these in the last 48h on 200k user spread over different device types and iOS versions (>=9).

**Comment by mertid** [comment]
okay. Ill keep digging. I can't reproduce locally yet either. Hope to have a solution by EOD

**Comment by mertid** [comment]
Hey Erik.

I believe I have tracked down the issue. I will release 5.1.2 by end of the week with updates.

**Comment by eriksundin** [comment]
That's great news, looking forward to the release.
Thanks.

**Comment by eriksundin** [comment]
Any update on this one @mertid ?

**Comment by mertid** [comment]
Still working on the update. Should be this week. Ill keep you posted. Sorry for the delay.

**Comment by eriksundin** [comment]
Hi @mertid. Sorry for pushing :) Have you guys made any progress on this issue?
Also, if you have more details on the conditions that cause the crash so that we can patch around it for now that would be helpful! Thanks

**Comment by mertid** [comment]
Hi Erik. Sorry the delay. 5.1.2 is in qa as we speak. One of the issues was around saving corrupt dispatches to persistence. We have set protections around this in the new release. I Will update you as soon as we release. Thank you for your patience.

**Comment by eriksundin** [comment]
That's great, thanks again @mertid.

**Comment by mertid** [comment]
Hi @eriksundin. 5.1.2 is out via the repo link or CocoaPods! Thank you for your patience.

**Comment by eriksundin** [comment]
Great, will upgrade and close this once verified in our next release. Thanks

**Comment by mertid** [comment]
@eriksundin have you had a chance to test the update?

**Comment by eriksundin** [comment]
Unfortunately not, our release got postponed so we have not yet had the chance to battle test the new version. I'll close this issue and re-open if needed later on.
