### ISSUE TITLE
Logging to the device console?

### ISSUE THREAD

**Issue by JALsnipe** [Tealium/tealium-ios#30]
Even when setting a `TEALConfiguration` instance's environment to "dev" I only see Tealium logs in the lldb log in Xcode and not on the iOS System logs (through Xcode -> Devices -> [iOS Device] -> Console) or in the [iOS Console app](https://lemonjar.com/iosconsole/).  Is there a setting to enable Tealium-specific logging on the device level?

For reference, I'm looking to see logs like:

```
TEALIUM iOS 5.0.4: instance com.myapp.dev: Queued dispatch.
2017-02-03 13:15:21.574 MyApp[1364:442689] TEALIUM iOS 5.0.4: instance com.myapp.dev: Dispatch: 
 Dispatch type: link 
 Dispatch service: (none yet assigned) 
 datasources payload: {
 ...
}
```

in the device console.

Thanks.

**Comment by craigrouse** [comment]
@JALsnipe interesting... I have definitely seen logging in the device console before. Let me verify and get back to you. Sorry for the delayed response on this question.

**Comment by mertid** [comment]
@JALsnipe  Please try our latest release (5.1.3)
