### ISSUE TITLE
Disable logging to console

### ISSUE THREAD

**Issue by KITSDavidHardiman** [Tealium/tealium-ios#31]
I might be missing something obvious, but how do I disable the Xcode console logging from the tealium library? I'm not seeing any obvious API on either `Tealium` or `TEALConfiguration`. I only want to see tealium's log output when I'm working on my analytics implementation. The rest of the time I need it off so I can see my own useful debug logging.

**Comment by jalakoo** [comment]
Hi @KITSDavidHardiman,
The logging is controlled from the accounts Mobile Publish Settings (MPS) found in the TIQ dashboard.  If those settings have been left in the default mode then you can also change the log level by changing the 'environment' in your configuration used to initialize the library:

- dev : verbose logging
- qa :  warnings and errors only
- prod : errors only

So, if you do not have access or want to change the TIQ MPS setting; change the 'environment' String option to 'prod' for the time being for minimum log output.  

Otherwise, change the MPS log override setting from 'default' to 'none'.

We do realize this is confusing and plan to update the configuration api to permit better developer control in an upcoming release.

**Comment by KITSDavidHardiman** [comment]
Thanks @jalakoo. I've changed the log setting to silent - do not log in TIQ MPS but I'm still seeing logging. Does it take a while to propagate so the device library can pick it?

Re the future plans, let me add a +1 to that feature. The log levels are certainly sensible, it'd just be really nice to have a `logLevel` property so we can turn it on and off in Xcode as required.

**Comment by jalakoo** [comment]
Hmm. Should only take a few moments at most.  If the MPS override is still not working, then I recommend changing the 'environment' string to 'prod' for the time being.

**Comment by KITSDavidHardiman** [comment]
I'm pretty new to tealium. Is there any impact to using `prod` when we're not actually in production yet?

**Comment by craigrouse** [comment]
@KITSDavidHardiman it's recommended to use dev or qa in your dev builds to keep them separate from your production builds, which will allow your business users to separate their analytics reporting and avoid having test data appear in production reports.

Additionally, keeping the environments separate, means you can make changes in Tealium on the dev/qa environment without affecting the production app.

Other than that, there is technically no difference between dev/qa/prod; they will all behave in the same way and there's nothing to stop you from using "prod" on a dev build, it's just not recommended for the reasons mentioned above.

**Comment by KITSDavidHardiman** [comment]
Hi @craigrouse .
That leaves me with a big problem then. I can't realistically merge my branch with Tealium integration in it as noisy as it is. For my team who might want to see their own logging, tealium set on dev or qa just totally obscures what they're trying to see. And the SDK doesn't respect the silent override I've set in TIQ. Is there somewhere I should be logging this as an official support request so I can get it addressed as a high priority? I'm guessing a GitHub issue isn't your preferred support platform.

**Comment by craigrouse** [comment]
@KITSDavidHardiman Please log this as a support ticket via support@tealium.com, and be sure to give us your account and profile information. We will then be able to investigate your specific issue with logging and hopefully get it resolved for you.

**Comment by KITSDavidHardiman** [comment]
Thanks @craigrouse I've done that. Will close this issue.

**Comment by chefnobody** [comment]
@craigrouse Has the issue @KITSDavidHardiman brought up been addressed in a subsequent build? If so, which? This is a serious problem for developers who do not have access to the TIQ console or are not at all allowed to change any of its settings. Our logs are totally unusable at this point.

**Comment by KITSDavidHardiman** [comment]
Hi @chefnobody . See https://github.com/Tealium/tealium-ios/blob/master/TealiumIOS.framework/Headers/TEALConfiguration.h#L49. Should be in the latest version of the library. I've not used it myself, we got the TIQ setting working, but it looks like it should work...

**Comment by chefnobody** [comment]
Sure. Thank you. I will take look.... I guess iOS devs could always wrap their Tealium config in DEBUG configuration flagging code like this:

```
#if (defined(CONFIGURATION_DEBUG) || TARGET_IPHONE_SIMULATOR) == false
  // set up logging

#endif

```

**Comment by craigrouse** [comment]
@chefnobody Yes, the issue has been fixed as @KITSDavidHardiman said. Please don't hesitate to let us know if you have any issues with the new method.

**Comment by chefnobody** [comment]
This works. Thanks!

```
[configuration setLogLevel:TEALLogLevelDev];
```

**Comment by craigrouse** [comment]
Thanks for the confirmation @chefnobody
