### ISSUE TITLE
Tealium Lifecycle Tagged as 5.1.3 but 5.1.2 available in master 

### ISSUE THREAD

**Issue by djbalakrishnan** [Tealium/tealium-ios#35]
Hi Team,
I have notification  as new version available for the tealium lifecycle 5.1.3 committed and tagged by @mertid , 
<img width="976" alt="screen shot 2017-02-27 at 6 56 13 pm" src="https://cloud.githubusercontent.com/assets/1589922/23495432/9ce1c806-ff3e-11e6-9f48-b863476227d2.png">

but latest version not available in master it still have 5.1.2, kindly clarify its 5.1.3 to still 5.1.2 is official Life cycle version 

<img width="984" alt="screen shot 2017-02-27 at 7 37 31 pm" src="https://cloud.githubusercontent.com/assets/1589922/23495431/9cb0afdc-ff3e-11e6-9be6-b9af93acd103.png">

Thanks in Advance

**Comment by mertid** [comment]
Thank for bringing this to our attention. I made an update that should be more clear.
