### ISSUE TITLE
event_name not being populated on latest version of the Tealium SDK

### ISSUE THREAD

**Issue by JALsnipe** [Tealium/tealium-ios#36]
After upgrading from TealiumIOS 5.0.4 and TealiumIOSLifecycle 5.1.2 to TealiumIOS and TealiumIOSLifecycle 5.1.3, we're seeing an issue where `event_name` is not being populated.  Were there any changes to `event_name` between these Tealium versions?

**Comment by jalakoo** [comment]
@JALsnipe Yes, the 'event_name' key was replaced with 'tealium_event' starting with version 5.1.0. 

Was supposed to be marked for deprecation but was accidentally just removed instead.  It contains the exact same value so if you're using TIQ, can simply add 'tealium_event' and map it to wherever 'event_name' was previously mapped (no need to remove 'event_name' if needing to support earlier builds).

**Comment by JALsnipe** [comment]
Thanks, we now fire both `event_name` and `tealium_event`.
