### ISSUE TITLE
Warning: duplicate definition of category 'WatchKit' on interface 'Tealium'

### ISSUE THREAD

**Issue by yoojinhill** [Tealium/tealium-ios#38]
We are seeing a bunch of warnings for:

- TealiumIOS  5.2.1 
- Xcode 8.3

Obviously we prefer not to see these errors.

```
<built-in>:2:14: note: in module 'TealiumIOS' imported from <built-in>:3:

Pods/Headers/Public/TealiumIOS/TealiumIOS/Tealium+WatchKit.h:13:12: warning: duplicate definition of category 'WatchKit' on interface 'Tealium'

Pods/Headers/Public/TealiumIOS/TealiumIOS/Tealium+TagManagement.h:13:12: warning: duplicate definition of category 'TagManagement' on interface 'Tealium'

Pods/Headers/Public/TealiumIOS/TealiumIOS/Tealium+Collect.h:13:12: warning: duplicate definition of category 'Collect' on interface 'Tealium'

Pods/Headers/Public/TealiumIOS/TealiumIOS/TEALConfiguration+TagManagement.h:11:12: warning: duplicate definition of category 'TagManagement' on interface 'TEALConfiguration'

Pods/Headers/Public/TealiumIOS/TealiumIOS/TEALConfiguration+Collect.h:26:12: warning: duplicate definition of category 'Collect' on interface 'TEALConfiguration'
```

**Comment by jalakoo** [comment]
Thanks @yoojinhill, 

A ticket has been made for this, we'll look into this during the next update cycle.

**Comment by jalakoo** [comment]
Hi @yoojinhill, I'm presuming you're already using:

`pod "TealiumIOS"`

in your podfile.  I just tried fresh pod installs on 2 separate sample apps (1 Swift, 1 Objective-c) and was unable to produce the reported warnings above using XCode 8.3.2.

Is there any additional info you could pass along that may help us debug?

**Comment by yoojinhill** [comment]
I don't see the warnings either with XCode 8.3.2. I'm guessing it's an Xcode 8.3 issue??

This issue can be closed.

Thanks!
