### ISSUE TITLE
Tealium 5.2.1. Memory leaks 

### ISSUE THREAD

**Issue by krin-san** [Tealium/tealium-ios#40]
Our app with TealiumIOS inside leaks ~3 KB RAM on each new playback session (a new Tealium instance is creating) through the TealiumIOS 5.2.1 library. I created a demo app to isolate Tealium framework from our app code and got the same leaks in profile (Instruments) app.

Demo app sources: https://drive.google.com/open?id=0Bw-iyZEU0iYXYncyYmR4QjF4R0E

![tealeak instruments 25 clicks](https://cloud.githubusercontent.com/assets/2318002/25692438/4633f3fa-30ab-11e7-9ac8-fd82533aa288.png)

**Comment by craigrouse** [comment]
@krin-san Thanks for reporting this. Could you please send a private email referencing this issue to support@tealium.com and let us know your tealium account/profile name so that we can rule out any bad config in your Tealium iQ profile?

**Comment by krin-san** [comment]
@craigrouse, sorry for the delay. Message is sent.
Also this delay helps to locate a leak reason which is described in email as well.

**Comment by jonathanswong** [comment]
Hi @krin-san . We were able to locate the issue and it will be fixed in the next release.  Thanks.

**Comment by jonathanswong** [comment]
@krin-san Release 5.3.1 is available.  Please let us know if this problem still persists and file a new issue.  Thank you.
