### ISSUE TITLE
`visitorIDCopy` returns nil although it exists in `persistentDataSourcesCopy`

### ISSUE THREAD

**Issue by haitham-reda** [Tealium/tealium-ios#42]
Always getting nil here, although both `tealium_visitor_id` and `visitor_id` are not empty.
is it build configuration related ? e.g. return nil for `DEBUG` build or so forth ?
lib version 5.2.1.

Thanks.

**Comment by jalakoo** [comment]
Hi @haitham-reda,

visitorIDCopy should only return nil if the Collect service is disabled.  Though it might also return nil if the lib is not finished initializing at the time of the copy request. As an alternate, can call:

`NSString * visitorIDCopy = [[Tealium instanceForKey:@"your_instance_id"] persistentDataSourcesCopy][TEALDataSourceKey_Tealium_Visitor_Id];`

**Comment by haitham-reda** [comment]
thanks @jalakoo , i'm already using `[persistentDataSourcesCopy valueForKey:@"tealium_visitor_id"]`, so you advice that i stick to that ? or in this case: to use the `TEALDataSourceKey_Tealium_Visitor_Id ` constant instead.

**Comment by jalakoo** [comment]
@haitham-reda Correct.  Either or.  Using the constant is usually recommended, in the unlikely case the string value for 'tealium_visitor_id' is changed, using the constant would save you the trouble of having to manually update it.
