### ISSUE TITLE
Error Code 406 on every dispatch

### ISSUE THREAD

**Issue by langerhans** [Tealium/tealium-ios#44]
Hi,

we are currently facing an issue with the Tealium Tag Management. In our Android App we use equal settings in the Tealium Config for the Mobile SDK and it works fine there. Just Tag Management, not Tealium Collect.

We pretty much use a default instance much like your samples. Each and every tracking request shows the following error in the completion handler:
![pasted image at 2017_05_31 15_35](https://cloud.githubusercontent.com/assets/5160000/26634653/9f0996d4-4617-11e7-921b-acc166b5828f.png)

According to the docs this is "normal" but we never see the events incoming in the backend / through a proxy. 
So the question is what could cause this? I assumed the dispatches would at some point be sent, but that never happens.

**Comment by jalakoo** [comment]
Hi @langerhans,

Does your TIQ Mobile Publish Configuration look like the following?

http://res.cloudinary.com/dfpz40r7j/image/upload/v1496249405/TIQ_MobilePublishSettings_fbax1u.png

And just to clarify, you are not the Collect service or a Collect Tag in your Tag Management setup?

**Comment by langerhans** [comment]
Thanks for the quick reply! We don't have Tealium Collect enabled. That is the difference I see to your screenshot. The config is pretty much the same as for Android where we also don't use Tealium Collect. Is there a difference between the two systems here?  
As for your second question, I'd have to check back with our analytics team about the specifics but I was told that we are not using Tealium Collect anywhere at the moment.

**Comment by craigrouse** [comment]
@langerhans did you ever resolve this? I'm 99% sure it's a problem with your publish settings. If it's resolved, kindly close the issue when you have a moment, or let us know if you need further support.

**Comment by langerhans** [comment]
@craigrouse Sorry for not getting back to this. We seem to have indded "solved" this issue. I quote that since I was just proxying for the iOS team and all I know is that it seems to work again. I'm fairly sure you're right though and it was an issue with the publish settings. I'll close here for now. Thank you for your support though!

**Comment by craigrouse** [comment]
No problem at all - thanks for confirming @langerhans.
