### ISSUE TITLE
Tealium 5.3.0 - no pod released

### ISSUE THREAD

**Issue by renehellmann** [Tealium/tealium-ios#48]
Hey,
there is still no pod for 5.3.0

Best
Rene

**Comment by craigrouse** [comment]
@renehellmann sorry about that. We're hoping to get it released today.

**Comment by jalakoo** [comment]
@renehellmann Should be up now.

**Comment by renehellmann** [comment]
Perfect, it's available!
Thanks (@craigrouse @jalakoo )!

Best
Rene
