### ISSUE TITLE
Tealium use of CFBundleShortVersionString and ignorance of CFBundleVersion

### ISSUE THREAD

**Issue by daveanderson** [Tealium/tealium-ios#52]
The Apple documentation for `CFBundleShortVersionString` states
> CFBundleShortVersionString (String - iOS, macOS) specifies the release version number of the bundle, which identifies a released iteration of the app.

https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html#//apple_ref/doc/uid/20001431-111349

The Apple documentation for `CFBundleVersion` states
> CFBundleVersion (String - iOS, macOS) specifies the build version number of the bundle, which identifies an iteration (released or unreleased) of the bundle.

https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html#//apple_ref/doc/uid/20001431-102364

The fundamental difference is that `CFBundleShortVersionString` identifies the _release_ while `CFBundleVersion` identifies the _build_.

For compatibility with TestFlight and the iOS AppStore we have an app where for a specific _version_ (e.g. `1.0`) we have an incrementing integer identifying the _build_ (e.g. `27`). Within TestFlight these are visually represented as `Version 1.0 (27)`.

As we perform our analytics implementation with Tealium our validation of the analytics occurs on a build-by-build basis. In this manner it is **necessary** that we segment the reporting based on the combination of _version_ **and** _build_ number, so that our confirmation is accurate and specific to a given build.

We have identified that Tealium is sending **only** the value of `CFBundleShortVersionString` and is ignoring the highly significant and valuable value of `CFBundleVersion`.

e.g. we see `    "app_version": "1.0",` being included in the data sent to Tealium.

## Expected Behaviour

We would expect that the Tealium iOS SDK either 

* be updated to automatically send **both** `CFBundleShortVersionString` **and** `CFBundleVersion` in the format of `"app_version": "1.0 (27)",`

or

* allow configuration such that **both** `CFBundleShortVersionString` **and** `CFBundleVersion` are sent in the format of `"app_version": "1.0 (27)",`

## Current Behaviour

The Tealium iOS SDK does not send the value of `CFBundleVersion`, which prevents us from inspecting, reporting and validating our analytics on a _build by build_ basis. Our reporting ends up showing information for all builds of an app, which makes confirmation of the implementation _changes_ very very difficult.

**Comment by craigrouse** [comment]
@daveanderson Thanks for highlighting this. I have created an action internally to take a look at this with the next release. In the meantime, you can of course send the CFBundleVersion as a variable, along with your other data. I recommend setting the bundle version as a volatile variable, which will ensure it gets sent along with each tracking call, without you having to manually specify it every time. Volatile data is persisted until the app is relaunched, which I think is perfect for your use case.

Let me know if you need anything else.

**Comment by daveanderson** [comment]
Thank you @craigrouse for the prompt response. Do you have a snippet of the proper technique for setting a volatile variable?

**Comment by craigrouse** [comment]
@daveanderson here's an example that would set a static string value of "1.1.1" for the key name "build_version", but you can substitute these for the actual names and values you wish to pass:

`[[Tealium instanceForKey:@"main"] addVolatileDataSources:@{@"build_version":@"1.1.1"}];`

You will also need to substitute "main" for your real Tealium instance key (which as you probably know, is an arbitrary string value used to uniquely address the specific instance of our library you created in the initialization phase). The full API docs are here: http://tealium.github.io/tealium-ios/Classes/Tealium.html

**Comment by daveanderson** [comment]
That is perfect and very helpful. Thanks!

**Comment by craigrouse** [comment]
You're welcome @daveanderson. I will close this issue for now, but look out for this feature in a coming release.
