### ISSUE TITLE
Too many symbol files when submitting build to iTunes Connect

### ISSUE THREAD

**Issue by JALsnipe** [Tealium/tealium-ios#55]
Hi, I'm seeing this issue when trying to upload new builds to iTunes Connect:

> **Too many symbol files** - These symbols have no corresponding slice in any binary [1306BCB7-953D-3FC5-956E-40B85B8986A1.symbols, 1E4D6E88-04C1-35F7-BAB4-06A099EEB295.symbols, E7EB083C-E638-3143-AD6E-F752EA48179E.symbols, EA990B6D-CAF9-3B87-8D99-D04A4FA36537.symbols]

`dwarfdump` shows that Tealium is the culprit:
```
➜  dSYMs dwarfdump --uuid *
# ...
UUID: 1306BCB7-953D-3FC5-956E-40B85B8986A1 (x86_64) TealiumIOS.framework.dSYM/Contents/Resources/DWARF/TealiumIOS
UUID: 1E4D6E88-04C1-35F7-BAB4-06A099EEB295 (x86_64) TealiumIOSLifecycle.framework.dSYM/Contents/Resources/DWARF/TealiumIOSLifecycle
UUID: E7EB083C-E638-3143-AD6E-F752EA48179E (i386) TealiumIOSLifecycle.framework.dSYM/Contents/Resources/DWARF/TealiumIOSLifecycle
UUID: EA990B6D-CAF9-3B87-8D99-D04A4FA36537 (i386) TealiumIOS.framework.dSYM/Contents/Resources/DWARF/TealiumIOS
# ...
➜  dSYMs
```

We are using CocoaPods, TealiumIOS and TealiumIOSLifecycle 5.3.0.  Any ideas?

**Comment by craigrouse** [comment]
@jalsnipe I'll take a proper look at this tomorrow, but does this stackoverflow post help at all? https://stackoverflow.com/questions/34313049/too-many-symbol-files-warnning-when-submitting-app

Let me know.

**Comment by JALsnipe** [comment]
I'll double check our valid architectures and get back to you.

**Comment by fjtrujy** [comment]
I have exactly the same issue.

Look to be just Teallium.

I have received the next mail from Apple:

```
We have discovered one or more issues with your recent delivery for "XXXXXXXXXXXX". Your delivery was successful, but you may wish to correct the following issues in your next delivery:

Too many symbol files - These symbols have no corresponding slice in any binary [1306BCB7-953D-3FC5-956E-40B85B8986A1.symbols, EA990B6D-CAF9-3B87-8D99-D04A4FA36537.symbols]
```

I went to the folder where the dSYMs files are for that archive. And the I executed the next command:

`dwarfdump --uuid *`

It shows the next content

```
UUID: 8244B580-B582-3122-8AF6-DF5E2F1E1EFA (armv7) AirshipKit.framework.dSYM/Contents/Resources/DWARF/AirshipKit
UUID: 581D6C83-6020-3F2B-BB73-99976928EC4D (arm64) AirshipKit.framework.dSYM/Contents/Resources/DWARF/AirshipKit
UUID: 0AAB69D8-7EBB-38E6-8AC5-F8F67BB5FC5B (armv7) DKCarouselView.framework.dSYM/Contents/Resources/DWARF/DKCarouselView
UUID: 3E06714B-6539-3BBC-8EA4-40D8CE50502D (arm64) DKCarouselView.framework.dSYM/Contents/Resources/DWARF/DKCarouselView
UUID: AE0D5E04-86CD-304B-BAF8-00911F65B97F (armv7) DRKonamiCode.framework.dSYM/Contents/Resources/DWARF/DRKonamiCode
UUID: BE54CF3C-242B-3F76-BBAF-33C5EB79C489 (arm64) DRKonamiCode.framework.dSYM/Contents/Resources/DWARF/DRKonamiCode
UUID: 6C0AF028-1D5B-35C2-AFD3-EAF1831C455D (armv7) FLAnimatedImage.framework.dSYM/Contents/Resources/DWARF/FLAnimatedImage
UUID: 73334FB3-4DDA-368C-AA17-914DDCC21CCF (arm64) FLAnimatedImage.framework.dSYM/Contents/Resources/DWARF/FLAnimatedImage
UUID: 02BDAEE1-0DCD-3163-B8D8-A57E0B7B87C3 (armv7) FLEX.framework.dSYM/Contents/Resources/DWARF/FLEX
UUID: 04FFEE2F-ED8D-320B-9867-4291FA2D4D95 (arm64) FLEX.framework.dSYM/Contents/Resources/DWARF/FLEX
UUID: 8935DF81-9C45-36AD-9839-73F051295462 (armv7) FXReachability.framework.dSYM/Contents/Resources/DWARF/FXReachability
UUID: 500E489F-3365-3D38-A286-52526DCB1402 (arm64) FXReachability.framework.dSYM/Contents/Resources/DWARF/FXReachability
UUID: 7A7C272B-5262-3E3F-B470-A941DAD5B7F3 (armv7) GBDeviceInfo.framework.dSYM/Contents/Resources/DWARF/GBDeviceInfo
UUID: CA9C7C47-EE43-39C5-822C-BFC221A58BC6 (arm64) GBDeviceInfo.framework.dSYM/Contents/Resources/DWARF/GBDeviceInfo
UUID: 1AA205FF-0E69-34A1-81E6-5543E589D80D (armv7) JJMaterialTextField.framework.dSYM/Contents/Resources/DWARF/JJMaterialTextField
UUID: 6825F834-AE45-3D51-B70E-C9C4DDD52576 (arm64) JJMaterialTextField.framework.dSYM/Contents/Resources/DWARF/JJMaterialTextField
UUID: 84661836-083D-375B-A5CA-1830206106EE (armv7) JRSwizzle.framework.dSYM/Contents/Resources/DWARF/JRSwizzle
UUID: A42F50A2-71D1-39A1-9145-3DC286439138 (arm64) JRSwizzle.framework.dSYM/Contents/Resources/DWARF/JRSwizzle
UUID: 923AD854-AE08-3AE3-9029-66D4A12100C7 (armv7) JVFloatLabeledTextField.framework.dSYM/Contents/Resources/DWARF/JVFloatLabeledTextField
UUID: CF0CB315-D135-3E23-A6A7-6166353B2F10 (arm64) JVFloatLabeledTextField.framework.dSYM/Contents/Resources/DWARF/JVFloatLabeledTextField
UUID: 5D0D3FC8-AF2C-3804-9452-F757CC9BD135 (armv7) NSLogger.framework.dSYM/Contents/Resources/DWARF/NSLogger
UUID: 694012E7-8E29-315C-8F6B-66BB22E9ED77 (arm64) NSLogger.framework.dSYM/Contents/Resources/DWARF/NSLogger
UUID: 8C528E65-18A2-38C3-A428-8A50D184D0CC (armv7) SDWebImage.framework.dSYM/Contents/Resources/DWARF/SDWebImage
UUID: 9DAF575F-7F4D-32FE-A498-B5C940AFB6E4 (arm64) SDWebImage.framework.dSYM/Contents/Resources/DWARF/SDWebImage
UUID: D096D314-B4F1-399E-A201-11BA5D4DFABC (armv7) SocketRocket.framework.dSYM/Contents/Resources/DWARF/SocketRocket
UUID: 6DA1572C-9AD0-3EC7-A369-324E3F0B0BA3 (arm64) SocketRocket.framework.dSYM/Contents/Resources/DWARF/SocketRocket
UUID: 79D8E27F-FBD8-37F2-A600-848EFC9AB572 (armv7) TTTAttributedLabel.framework.dSYM/Contents/Resources/DWARF/TTTAttributedLabel
UUID: 3C65C808-F600-310A-BC19-D25867DA6401 (arm64) TTTAttributedLabel.framework.dSYM/Contents/Resources/DWARF/TTTAttributedLabel
UUID: EA990B6D-CAF9-3B87-8D99-D04A4FA36537 (i386) TealiumIOS.framework.dSYM/Contents/Resources/DWARF/TealiumIOS
UUID: 1306BCB7-953D-3FC5-956E-40B85B8986A1 (x86_64) TealiumIOS.framework.dSYM/Contents/Resources/DWARF/TealiumIOS
UUID: CF845CCB-4E31-379F-8835-DA3B16734722 (armv7) TealiumIOS.framework.dSYM/Contents/Resources/DWARF/TealiumIOS
UUID: B353F154-B6B4-3FCA-AA18-C18E400EC139 (arm64) TealiumIOS.framework.dSYM/Contents/Resources/DWARF/TealiumIOS
UUID: 8091E9F3-EC64-3F06-A3F9-08354090ACD4 (armv7) UICKeyChainStore.framework.dSYM/Contents/Resources/DWARF/UICKeyChainStore
UUID: 46DB8B43-8040-3FAE-8FCD-0FFA22B933CE (arm64) UICKeyChainStore.framework.dSYM/Contents/Resources/DWARF/UICKeyChainStore
UUID: A1031A55-EF84-38F2-90A3-F90CD940324C (armv7) UINavigationControllerWithCompletionBlock.framework.dSYM/Contents/Resources/DWARF/UINavigationControllerWithCompletionBlock
UUID: 9BAFDF70-B9F1-316D-958F-592FDB2A5EA0 (arm64) UINavigationControllerWithCompletionBlock.framework.dSYM/Contents/Resources/DWARF/UINavigationControllerWithCompletionBlock
UUID: EB0F5DCB-4450-3E37-8EC3-F8D239837B56 (armv7) UIScrollSlidingPages.framework.dSYM/Contents/Resources/DWARF/UIScrollSlidingPages
UUID: 98BD6D49-BB21-356E-A7FE-65086EA58866 (arm64) UIScrollSlidingPages.framework.dSYM/Contents/Resources/DWARF/UIScrollSlidingPages
UUID: 38F18106-E8F1-37C8-B8CB-DB5C189470A5 (armv7) UIWebView_HeaderFooter.framework.dSYM/Contents/Resources/DWARF/UIWebView_HeaderFooter
UUID: F010D49E-3A88-3ABB-BAA2-E4ADA1BB9FB8 (arm64) UIWebView_HeaderFooter.framework.dSYM/Contents/Resources/DWARF/UIWebView_HeaderFooter
UUID: A6634644-EC03-3557-B781-E0C0B675CC72 (armv7) WebViewJavascriptBridge.framework.dSYM/Contents/Resources/DWARF/WebViewJavascriptBridge
UUID: 33F8C399-78E6-303B-8F6E-141DC4BEBF9B (arm64) WebViewJavascriptBridge.framework.dSYM/Contents/Resources/DWARF/WebViewJavascriptBridge
UUID: 663808B5-971F-32F7-8CDF-23E82D302A17 (armv7) YIInnerShadowView.framework.dSYM/Contents/Resources/DWARF/YIInnerShadowView
UUID: 7EAD0C47-B066-3E33-AD18-9B3A05FF5006 (arm64) YIInnerShadowView.framework.dSYM/Contents/Resources/DWARF/YIInnerShadowView
UUID: 070EFECD-9C0D-3802-8907-699310196206 (armv7) iRate.framework.dSYM/Contents/Resources/DWARF/iRate
UUID: F49ED7B4-F9E8-3060-8674-2D4ABB526A3D (arm64) iRate.framework.dSYM/Contents/Resources/DWARF/iRate
```


If you see it is all the PODs that my App has, the unique one that contains `i386` and `x86_64` is `Teallium`.

Thanks

**Comment by fjtrujy** [comment]
Hello again,

@JALsnipe sorry to disturb you, but do you have any clue?

Thanks in advance

**Comment by ThomGru** [comment]
Hello,

we detected the exactly same issue like @fjtrujy. 
Do you have any updates?

Thanks.

**Comment by JALsnipe** [comment]
@fjtrujy Sorry for the late reply, we are moving away from Tealium so I my solution was to completely remove the library.  I don't have a fix for this but I think this needs to be addressed from Tealium's end.

**Comment by apats** [comment]
Same thing in here
```
UUID: EA990B6D-CAF9-3B87-8D99-D04A4FA36537 (i386) TealiumIOS.framework.dSYM/Contents/Resources/DWARF/TealiumIOS
UUID: 1306BCB7-953D-3FC5-956E-40B85B8986A1 (x86_64) TealiumIOS.framework.dSYM/Contents/Resources/DWARF/TealiumIOS
```

any chance of fixing this?

**Comment by craigrouse** [comment]
@apats Sorry this has taken so long to get round to fixing. It is the next thing we are going to address, and I hope to have a fix very soon.

**Comment by craigrouse** [comment]
@apats Just as a follow up on this, it seems this is related to a CocoaPods issue that was present when we uploaded the framework to CocoaPods, but has very recently been fixed: https://github.com/CocoaPods/CocoaPods/issues/7111#issuecomment-334855012

I'll post back here as soon as I've been able to rebuild the framework with the new CocoaPods version, and hopefully this will resolve the issue.

**Comment by apats** [comment]
@craigrouse great, thanks for the quick response!

**Comment by apats** [comment]
@craigrouse right now Cocoapods 1.4.0 is in beta, I'll try to update for a stable release as soon as it will be available. This issue might be fixed with that release.

**Comment by craigrouse** [comment]
@apats you're right - I was thinking this is something we could fix, but it actually should be taken care of by CocoaPods during the build process on your end. Let me know how you get on with the updated CocoaPods version. @JALsnipe @ThomGru @fjtrujy you might be interested by this development also. It seems like this issue is going to be fixed in the next CocoaPods release.

**Comment by JITENDRA7104** [comment]
Apples-MacBook-Air:dSYMs apple$ dwarfdump --uuid *
UUID: 0B523B17-252B-35C1-A94E-EC1B5FE7AC6E (armv7) FMDB.framework.dSYM/Contents/Resources/DWARF/FMDB
UUID: CAEE7D63-DEAA-3818-9778-F72F9996450F (arm64) FMDB.framework.dSYM/Contents/Resources/DWARF/FMDB
UUID: AF2AD82E-4205-380E-BD54-DF36BBD0D446 (arm64) Runner.app.dSYM/Contents/Resources/DWARF/Runner
UUID: 6D4E71D5-9B85-3D1F-9E36-ADF9C56BC827 (armv7) path_provider.framework.dSYM/Contents/Resources/DWARF/path_provider
UUID: 81EE44D4-84D2-3CF5-ADF2-C591D55EED00 (arm64) path_provider.framework.dSYM/Contents/Resources/DWARF/path_provider
UUID: 1202FC31-64F7-35A5-A83A-BE08401F5617 (armv7) share.framework.dSYM/Contents/Resources/DWARF/share
UUID: 981D1C08-8C59-3CE6-A3E8-B11D77A0BDAA (arm64) share.framework.dSYM/Contents/Resources/DWARF/share
UUID: 2DF3956E-9B95-398E-9A4C-19CDF609E899 (armv7) shared_preferences.framework.dSYM/Contents/Resources/DWARF/shared_preferences
UUID: F717C107-1650-38DB-A0FE-CCCE5C218C25 (arm64) shared_preferences.framework.dSYM/Contents/Resources/DWARF/shared_preferences
UUID: 2CE5B047-5CDC-3C9B-B5FF-106501E63EB7 (armv7) sqflite.framework.dSYM/Contents/Resources/DWARF/sqflite
UUID: DADC849B-26EF-3842-ABBF-ACD4E5B6711F (arm64) sqflite.framework.dSYM/Contents/Resources/DWARF/sqflite

**Comment by JITENDRA7104** [comment]
Too many symbol files - These symbols have no corresponding slice in any binary [0B523B17-252B-35C1-A94E-EC1B5FE7AC6E.symbols, 1202FC31-64F7-35A5-A83A-BE08401F5617.symbols, 2CE5B047-5CDC-3C9B-B5FF-106501E63EB7.symbols, 2DF3956E-9B95-398E-9A4C-19CDF609E899.symbols, 6D4E71D5-9B85-3D1F-9E36-ADF9C56BC827.symbols]

**Comment by JITENDRA7104** [comment]
Too many symbol files - These symbols have no corresponding slice in any binary [0B523B17-252B-35C1-A94E-EC1B5FE7AC6E.symbols, 1202FC31-64F7-35A5-A83A-BE08401F5617.symbols, 2CE5B047-5CDC-3C9B-B5FF-106501E63EB7.symbols, 2DF3956E-9B95-398E-9A4C-19CDF609E899.symbols, 6D4E71D5-9B85-3D1F-9E36-ADF9C56BC827.symbols]

**Comment by JITENDRA7104** [comment]
how to solve this error
when i submit app on app store then give me mail
Too many symbol files - These symbols have no corresponding slice in any binary [0B523B17-252B-35C1-A94E-EC1B5FE7AC6E.symbols, 1202FC31-64F7-35A5-A83A-BE08401F5617.symbols, 2CE5B047-5CDC-3C9B-B5FF-106501E63EB7.symbols, 2DF3956E-9B95-398E-9A4C-19CDF609E899.symbols, 6D4E71D5-9B85-3D1F-9E36-ADF9C56BC827.symbols]

**Comment by jonathanswong** [comment]
Are you seeing this issue @JITENDRA7104 ? If you are, please open a new issue as this issue was previously closed. Please provide what frameworks you are using, and which dependency manager you are using if any. Thank you.

**Comment by nimisha112** [comment]
I am getting the same issue
UUID: AC5D8FB2-8E28-3FE7-B346-37C2EDCE5C50 (arm64) AWSCore.framework.dSYM/Contents/Resources/DWARF/AWSCore
UUID: 89821C26-C106-3318-B918-2FA803DB4735 (arm64) AWSRekognition.framework.dSYM/Contents/Resources/DWARF/AWSRekognition
UUID: 171F68AF-7E72-358C-80AF-58F459C9244D (arm64) Alamofire.framework.dSYM/Contents/Resources/DWARF/Alamofire
UUID: 705F08EC-F544-3009-896C-5669A3635E69 (arm64) CBPinEntryView.framework.dSYM/Contents/Resources/DWARF/CBPinEntryView
UUID: 3DD08869-0F95-3A0D-878A-F63D2B397D23 (arm64) CryptoSwift.framework.dSYM/Contents/Resources/DWARF/CryptoSwift
UUID: 8174913E-0FF8-3CDE-8E12-F4FD05ED03BE (arm64) Cryptor.framework.dSYM/Contents/Resources/DWARF/Cryptor
UUID: 1D6AEF8B-A1E9-3BD1-878F-D518D681E1D6 (arm64) CryptorECC.framework.dSYM/Contents/Resources/DWARF/CryptorECC
UUID: 8D3C4644-B4A2-38D3-B4D1-A9D30D7CCE9B (arm64) CryptorRSA.framework.dSYM/Contents/Resources/DWARF/CryptorRSA
UUID: 5940D602-3548-3D07-8C2E-29E3A588D403 (arm64) DJCaptureButton.framework.dSYM/Contents/Resources/DWARF/DJCaptureButton

**Comment by nimisha112** [comment]
I have already tried Project -> Build Settings -> Debug Information Format
Set it to “DWARF” but if I do dwarfdump the above message shows again.

**Comment by nimisha112** [comment]
Tried post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ARCHS'] = '$ARCHS_STANDARD_64_BIT'
    end
  end
end

**Comment by craigrouse** [comment]
@nimisha112 none of those frameworks appears to be our framework (Tealium). Are you just asking this as a general question? Make sure you are using the latest version of CocoaPods, as this issue turned out to be a CocoaPods problem: https://github.com/CocoaPods/CocoaPods/issues/7111#issuecomment-334855012
Let me know if we can be of further assistance.
