### ISSUE TITLE
Crash on App Startup

### ISSUE THREAD

**Issue by michaelbrunek** [Tealium/tealium-ios#57]
Hello,

for some time now we experience a seldom crash which occurs after the app ist started. We already talked with one of your engineers via phone and he did not find any issues in our app.

Application Specific Information:
*** Terminating app due to uncaught exception 'NSGenericException', reason: '*** Collection <__NSDictionaryM: 0x1d023bfc0> was mutated while being enumerated.'

[crash_log.txt](https://github.com/Tealium/tealium-ios/files/1487870/crash_log.txt)

**Comment by jonathanswong** [comment]
@Dirog We found a fix for this issue and it should be fixed in our next release.  Thanks.

**Comment by jonathanswong** [comment]
@Dirog Release 5.3.1 is available.  Please let us know if this problem still persists and file a new issue.  Thank you.

**Comment by cnerkar1859** [comment]
@jonathanswong - I am getting this error for pod "TealiumIOS", "5.8.2" , Manually app opens perfectly fine , am facing this issue while running the app with appium - 1.22.0 , Xcode 13.2.1 , I tried to downgrade all the versions to see if there is an issue from the appium side, but am suspecting issue is with Tealium webview library , I am attaching the logs, It will be really helpful if you could have a look , i have spent lot of time on it, I am not able to resolve the issue as app is crashing at the launch itself.
[crash_log.txt](https://github.com/Tealium/tealium-ios/files/8057398/crash_log.txt)
