### ISSUE TITLE
Error Integrating TealiumWATCHOSExtension: Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by lohithkorp** [Tealium/tealium-ios#59]
As per the documentation provided in [link here](https://community.tealiumiq.com/t5/Mobile-Libraries/Tealium-for-watchOS/ta-p/11487) , I have added the framework to my project (which is already using Tealium for the iOS app), and I get the following error when I try to run/build.
```

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_TEALWKExtension", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_TEALWKExtensionConfiguration", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
I am using Xcode 9.1 at the moment, and faced the same problem with Xcode 9.2, 9.0 and 8.3.2.

Am I missing anything, may be that is missed in the documentation?

**Comment by jonathanswong** [comment]
Hi @lohithkorp , are you using `#import <TealiumWATCHOSExtension/TealiumWATCHOS.h>` or `@import TealiumWATCHOSExtension` in your Watch App Extension?

**Comment by lohithkorp** [comment]
@jonwong-tealium - I am using `#import <TealiumWATCHOSExtension/TealiumWATCHOS.h>`

**Comment by jonathanswong** [comment]
@lohithkorp Which framework did you link, TealiumWATCHOSExtension or TealiumWATCHOSExtension_DevicesOnly?

**Comment by lohithkorp** [comment]
Using TealiumWATCHOSExtension

**Comment by jonathanswong** [comment]
Do you happen to have a build phase that is stripping the simulator in a build phase? If not, can you try removing the framework and redownloading it. Thank you.

**Comment by lohithkorp** [comment]
Could you please elaborate? 
I've actually tried removing the framework and redownloading it but with no luck.

**Comment by jonathanswong** [comment]
Our libraries contain simulator support. When you submit to the app store with simulator support, iTunes will issue an error. You can add a build phase to remove the simulator support as outlined [here](https://community.tealiumiq.com/t5/Tealium-for-iOS/Troubleshooting-Tealium-for-iOS/ta-p/11348
)

If in your Build Phases, you have a Run Script that is currently stripping out the simulator support, it could be the reason why you are seeing that error.

**Comment by lohithkorp** [comment]
Ok, now I see what you are saying. I am sure we don't have a Run script that strips out the simulator support.
(Yes, I am aware of the Itunes rejection of the build with simulator support. We haven't gone that far yet.)
I will spend some more time - verifying your inputs and also redownloading once again. Hope that should help.

**Comment by jonathanswong** [comment]
@lohithkorp Ok sounds good.  There is also a new release, 5.3.1, as of today that you can try.

**Comment by lohithkorp** [comment]
@jonwong-tealium : Things seem to work fine now, after I used the latest .framework from your github today.
I have a question though. I have two views to track now. And I believe they are working good. Where do I see that they are actually being tracked? Is it in the same account as my iOS app?

**Comment by jonathanswong** [comment]
@lohithkorp You can check the Xcode logs when you make the track calls.  If you are using TiQ, you can check the third party tag vendors' dashboard to see if the data is coming in (e.g. Google Analytics). You could enable UDH temporarily and see the data in live events or use a tool like Charles Proxy to monitor your network traffic. 

https://community.tealiumiq.com/t5/Mobile-Libraries/Debugging-Tealium-Mobile-Apps/ta-p/15508

**Comment by lohithkorp** [comment]
@jonwong-tealium - the Xcode logs doesn't show anything for the watch app, like they did for the iOS app. Here is what I have so far,
1. Added tealium to the project using pod - configuration, views,  events successful.
2. Added tealium watch os framework to the watch extension target. 

**TealiumWatchHelper.swift**
```
import Foundation
import TealiumIOS
import TealiumWATCHOSExtension

extension String : Error {}

/// Example of a shared helper to handle all 3rd party tracking services. This
/// paradigm is recommended to reduce burden of future code updates for external services
/// in general.
class TealiumWatchHelper : NSObject {    
    static let _sharedInstance = TealiumWatchHelper()
    var tealium : TEALWKExtension?
    var enableHelperLogs = true
    @objc class func sharedInstance() -> TealiumWatchHelper {
        return _sharedInstance
    }
    
    @objc func start() {
        
        // REQUIRED Config object for lib
        let config = TEALWKExtensionConfiguration()

        // OPTIONALLY set log level
        config.logLevel = TEALLogLevel.dev
        
        tealium = TEALWKExtension.newInstance(forKey: "tealium_main", configuration: config)
        
        // process a tracking call on the background queue
        // example tracking call - not required in production
        DispatchQueue.global(qos: .background).async {
            self.tealium?.trackView(withTitle: "WatchHelperReady_DEV", dataSources: nil)
        }
        
        // example tracking call - not required in production
        self.tealium?.trackView(withTitle: "WatchHelperReady_DEV", dataSources: nil)
        
    }
    
    // track an event
    @objc func track(title: String, data:[String:Any]?) {
        tealium?.trackEvent(withTitle: title, dataSources: data)
    }
    
    // track a screen view
    @objc func trackView(title: String, data:[String:Any]?) {
        tealium?.trackView(withTitle: title, dataSources: data)
        print("tracked view \(title)")
    }
    
    @objc func crash() {
        NSException.raise(NSExceptionName(rawValue: "Exception"), format:"This is a test exception", arguments:getVaList(["nil"]))
    }
}
```
Within my **ExtensionDelegate.swift**, I have below -
```
func applicationDidFinishLaunching() {
        // Perform any final initialization of your application.
        TealiumWatchHelper.sharedInstance().start()
    }
```
Within my **InterfaceController.swift** -> `**didReceiveApplicationContext**`, I have this -
```
TealiumWatchHelper.sharedInstance().trackView(title: "QR_Screen", data: nil)
                
                let myData: [String: Any] = ["userName": userName, "myQrValue": myQrValue, "myQrImage": myQrImage as! Data]
                
                if let userName = myData["userName"] as? String {
                    titleText.setText(userName)
                }
                
                if let myQrImage = myData["myQrImage"] as? Data {
                    logoImageView.setImageData(myQrImage)
                    logoImageView.setWidth(110.0)
                    logoImageView.setHeight(110.0)
                }
```

Also, I created a bridging header within my Watch Extension, and added #import `<TealiumWATCHOSExtension/TealiumWATCHOS.h>`

Do you see everything is proper or is there anything I am missing?

**Comment by lohithkorp** [comment]
**UPDATE**: We have added a Tealium Collect tag to the Tealium configuration, but the only events we are seeing in Event Feed are from the app, and we do not see any events from the watch.

**Comment by jonathanswong** [comment]
@lohithkorp Have you taken a look at the WatchOS sample: 
[WatchOS Catalog](https://github.com/Tealium/tealium-ios/tree/master/Samples/WatchOS_Catalog%2BTealium_ObjC)

If you edit the configuration in TealiumHelper.m to point to your account and run the watch app you can see track calls being made in UDH.

**Comment by lohithkorp** [comment]
Indeed, I have seen the WatchOSCatalog sample. 

Edit the configuration in TealiumHelper? Of the watch os extension? In that case, the Tealwkconfiguration doesn't have any options to add account details in there.

**Comment by jonathanswong** [comment]
@lohithkorp You are correct the TEALWKConfiguration does not have any options to pass for account details.  The TealiumHelper has the configuration.  

- Update TealiumHelper.m with your account details
- Run the sample app with watchOS extension
- Use the watchOS app and see track calls being made in UDH

Please let us know if you are still having issues.  Thanks.

**Comment by lohithkorp** [comment]
I think I am slightly confused here. Watch extension target has my tealiumWatchHelper.swift as code provided in one of my comments above. 

TealiumHelper.swift is in my ios target. Which already has the account details. 

Not sure what extra I need to add here. Request you to clear the confusion. Thank you :)

**Comment by jonathanswong** [comment]
@lohithkorp Then there is nothing you should need to do.  The account details only need to be configured in the TealiumHelper as part of your iOS target like you already did.  You should be able to see watchOS events in UDH.

**Comment by lohithkorp** [comment]
Not sure whats missing then :|
I dont see any views or events in udh

**Comment by jonathanswong** [comment]
@lohithkorp Is this with the sample app or your own app?

**Comment by lohithkorp** [comment]
It's with my own app

**Comment by jonathanswong** [comment]
@lohithkorp Can you try it with the sample app with your account details first to make sure that your account is setup correctly in UDH to receive live events?  Thanks.

**Comment by lohithkorp** [comment]
ok, I will try that. one question struck me now, watch extension only sends events? and not views?

**Comment by jonathanswong** [comment]
@lohithkorp You can track both views and events.

**Comment by lohithkorp** [comment]
ok, could you please validate the steps I followed to configure (posted in comments), if you haven't already?

**Comment by jonathanswong** [comment]
@lohithkorp Validate the code snippets you provided?  Did the sample app work with your account?

**Comment by lohithkorp** [comment]
yes, code snippets I provided. (sample app testing in progress)

**Comment by lohithkorp** [comment]
Didn't see any events coming in for the WatchCatalog app as well

**Comment by jonathanswong** [comment]
@lohithkorp Please contact support@tealium.com. The sample app with watchOS extension should work out of the box by just putting in your account details.
