### ISSUE TITLE
How can I get the last version via CocoaPods?

### ISSUE THREAD

**Issue by andreas-sommer-engenious** [Tealium/tealium-ios#63]
Hi there,
We have the library installed via cocoapods with this command in the podfile: pod 'TealiumIOS', '~> 5.3'
But we still get the version 5.3.0 and not the latest version 5.3.1, see the output:
"Installing TealiumIOS (5.3.0)"

Can somebody help me?
Thanks
Andreas

**Comment by craigrouse** [comment]
@andreas-sommer-engenious usually running `pod update` will help, otherwise you can forcibly clear the CocoaPods cache by removing its cache directory. See here for some sample code: https://stackoverflow.com/questions/46428752/how-to-clear-or-clean-specific-pod-cache
