### ISSUE TITLE
Question: Doing any method swizzling?

### ISSUE THREAD

**Issue by chefnobody** [Tealium/tealium-ios#7]
I haven't tried decompiling or inspecting your .Framework yet but thought I'd ask before I tried using it: Do you do any method swizzling? If so what methods are swizzled and when are those swizzled methods set up?

**Comment by jalakoo** [comment]
Hi chef,
There is no method swizzling in this version of the library.  4.x did, but that version is archived in a different repo altogether.

**Comment by chefnobody** [comment]
Great news! One last question: Does your .Framework doing anything else with the Obj-C runtime in a non-standard fashion that may affect consumers? Thanks again for the reply!

**Comment by jalakoo** [comment]
Nope, just some kvo to keep track of some internal objects.

**Comment by chefnobody** [comment]
👍
