### ISSUE TITLE
Spike in sessions & unique users reporting with `always` location permission

### ISSUE THREAD

**Issue by haitham-reda** [Tealium/tealium-ios#70]
hello, recently we have changed our location permission to add  `always allow`, then immediately we started to see unjustified spike in unique users & sessions on GA dashboard, any known issue here ? could the location updates in background be root cause of that ?
Thanks.

**Comment by jonathanswong** [comment]
Hi @haitham-reda , is this still an issue for you? If not I'll close the issue. Thanks.
