### ISSUE TITLE
Crash on application start

### ISSUE THREAD

**Issue by JuhaO81** [Tealium/tealium-ios#71]
Our application crashes on application start. So far we have seen this happening only once. Here is the crash log. We are using release 5.3.0. 

Thread 2 Crashed:
0   IOKit                                0x00000001882936d8 IOServiceAddMatchingNotification + 36
1   UIKit                                0x000000018e396334 -[UIDevice setBatteryMonitoringEnabled:] + 188
2   TealiumIOS                           0x00000001010cd604 +[TEALDeviceDataSources batteryLevelAsPercentString] (TEALDeviceDataSources.m:359)
3   TealiumIOS                           0x00000001010cc5c0 -[TEALDeviceDataSources mainThreadDataSources] (TEALDeviceDataSources.m:84)
4   TealiumIOS                           0x00000001010af684 -[TEALDataSources backgroundSafeDataSources] (TEALDataSources.m:72)
5   TealiumIOS                           0x00000001010b68c4 __50-[Tealium trackType:title:dataSources:completion:]_block_invoke (Tealium.m:186)
6   libdispatch.dylib                    0x0000000186ede9e0 _dispatch_call_block_and_release + 20
7   libdispatch.dylib                    0x0000000186ede9a0 _dispatch_client_callout + 12
8   libdispatch.dylib                    0x0000000186eecad4 _dispatch_queue_serial_drain + 924
9   libdispatch.dylib                    0x0000000186ee22cc _dispatch_queue_invoke + 880
10  libdispatch.dylib                    0x0000000186eecfa8 _dispatch_queue_override_invoke + 340
11  libdispatch.dylib                    0x0000000186eeea50 _dispatch_root_queue_drain + 536
12  libdispatch.dylib                    0x0000000186eee7d0 _dispatch_worker_thread3 + 120
13  libsystem_pthread.dylib              0x00000001870e7100 _pthread_wqthread + 1092
14  libsystem_pthread.dylib              0x00000001870e6cac start_wqthread + 0

**Comment by craigrouse** [comment]
@JuhaO81 please update to the latest version. This issue should be fixed in 5.3.2

**Comment by jonathanswong** [comment]
Closed due to inactivity.
