### ISSUE TITLE
Sessions increase after enabling background fetch

### ISSUE THREAD

**Issue by iurimatsuura** [Tealium/tealium-ios#72]
Hi,

After enabling `application(_:performFetchWithCompletionHandler:)` we've experienced a sessions increase in two analytics services we use: GA (via Tealium) and Adjust. 

Last week we reverted those changes and noticed a significant session decrease in Adjust but GA (via Tealium) remains the same.

My questions are:

1. Could `application(_:performFetchWithCompletionHandler:)` impact the behavior of your SDK?
2. As we see Adjust sessions going down, could the Tealium SDK cache some data and therefore we don't see a decrease in sessions in GA? Would there be a way to clean such cache?

We are using SDK v5.3.1.

Thanks in advance.

Iuri.

**Comment by jonathanswong** [comment]
Hi @iurimatsuura . Implementing `application(_:performFetchWithCompletionHandler:)` should not affect the Tealium SDK.  

If you are able to share some of your sample code in how you initialize and destroy the Tealium SDK, as well as some sample calls with our support team at support@tealium.com, we can take a better look at the issue. Thanks.

**Comment by jonathanswong** [comment]
Closed due to inactivity.
