### ISSUE TITLE
TealiumiOS is not safe for use in application extensions

### ISSUE THREAD

**Issue by CRoig** [Tealium/tealium-ios#74]
I am trying to run some tracking on an App Extension. After compilation I receive following warning:

```ld: warning: linking against a dylib which is not safe for use in application extensions: /Users/roigc/Documents/bvios/Pods/TealiumIOS/TealiumIOS.framework/TealiumIOS```

Is this planned to be fixed soon?

**Comment by jonathanswong** [comment]
Hi @CRoig . Our Objective-C library currently does not support this but our Swift library does. The Swift library is open sourced and you can change the **Require Only App-Extension-Safe API** Build Setting to **Yes**.

https://github.com/tealium/tealium-swift

**Comment by CRoig** [comment]
Thanks. This has been really helpful.
