### ISSUE TITLE
WatchOS extension missing required architecture arm64_32

### ISSUE THREAD

**Issue by mapierce** [Tealium/tealium-ios#81]
Xcode 10 introduces a new build architecture, named arm64_32, apparently used for watchOS 5 devices.

This doesn't seem to be currently supported in the Tealium WatchOS Extension

Running: 
`lipo -info .../TealiumWATCHOSExtension.framework/TealiumWATCHOSExtension`

Results in: 
`Architectures in the fat file: .../TealiumWATCHOSExtension.framework/TealiumWATCHOSExtension are: i386 armv7k`

This results in the project not being able to build and a `linker command failed with exit code 1`

**Comment by jonathanswong** [comment]
Hi @mapierce . Thank you for bringing this to our attention. We'll try to get out a fix ASAP.

**Comment by mapierce** [comment]
Hi @jonwong-tealium we're a little blocked with this, any idea when it'll be released?

**Comment by jonathanswong** [comment]
@mapierce Should be done today. Thank you for your patience.

**Comment by jonathanswong** [comment]
Hi @mapierce , the change is completed. Thank you for your patience and bringing this issue to our attention.
