### ISSUE TITLE
Disable Logging

### ISSUE THREAD

**Issue by AbdallaGomaa7** [Tealium/tealium-ios#9]
How can I disable logging for Tealium? I want the payloads to still be sent just don't want to see them on console

**Comment by jalakoo** [comment]
Log output is auto set depending on the environment used:
dev - all logs
qa - warnings and errors only
prod - errors only

These can also be overwritten by the Mobile Publish Setting found in your Tealium IQ's publish settings dialog box. Logs there can be set to the above options plus a 'none' section which will disable all logs, including errors.
