### ISSUE TITLE
[CRASH] TealiumIOSLifecycle | NSInvalidArgumentException -> NSDateFormatter

### ISSUE THREAD

**Issue by f-gonzalez** [Tealium/tealium-ios#90]
**Steps to reproduce:**
I followed the steps documented in the following link from the official documentation (just adding the .framework file, embed it and import it in the Helper class): https://community.tealiumiq.com/t5/Tealium-for-iOS/Lifecycle-Tracking-Module-for-iOS/ta-p/16333#toc-hId--445660433

After adding the framework and the import I am getting a crash when trying to launch the application, (removed app info):

**Stack Trace** 

TEALIUM iOS 5.4.6: : Log level set from local: dev
[8781:117288] TEALIUM iOS 5.4.6: Configuration: 

 === TEALConfiguration === 
( Compile time options )
account - datasource id:
account - name: ---
account - profile: ---
account - target environment:qa 
Autotracking lifecycle enabled:YES 
instance id:
override publish settings url: 
override publish url:
2018-12-05 13:26:44.705469-0300 [8781:117288] TEALIUM iOS 5.4.6: ----: Remote Publish Settings: 

 === TEALPublishSettings === 
( Remote settings from default )
_is_enabled:1 
battery_saver:1 
dispatch_expiration:-1 
enable_tag_management:0 
event_batch_size:1 
minutes_between_refresh:0 
mps version:5 
offline_dispatch_limit:100 
url:----
wifi_only_sending:0
2018-12-05 13:26:44.708299-0300 [8781:117288] -[NSDateFormatter initWithSafeLocale]: unrecognized selector sent to instance 0x600000d76fd0
2018-12-05 13:26:44.712762-0300 [8781:117288] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSDateFormatter initWithSafeLocale]: unrecognized selector sent to instance 0x600000d76fd0'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000105bd01bb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x000000010b400735 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000105beef44 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x0000000105bd4ed6 ___forwarding___ + 1446
	4   CoreFoundation                      0x0000000105bd6da8 _CF_forwarding_prep_0 + 120
	5   TealiumIOSLifecycle                 0x000000010ad93563 +[TEALLifecycleDataSources isoDateFormatter] + 64
	6   TealiumIOSLifecycle                 0x000000010ad9334b +[TEALLifecycleDataSources isoStringFromDate:] + 53
	7   TealiumIOSLifecycle                 0x000000010ad916ac +[TEALLifecycleDataSources lifecycleFirstLaunchPersistentData:] + 100
	8   TealiumIOSLifecycle                 0x000000010ad91baf +[TEALLifecycleDataSources newPersistentLifecycleDataSourcesForLaunchesAt:persistentData:priorPersistentData:] + 343
	9   TealiumIOSLifecycle                 0x000000010ad90ec2 +[TEALLifecycleDataSources newLifecycleDataSourcesForType:date:persistentData:priorPersistentData:] + 486
	10  TealiumIOSLifecycle                 0x000000010ad93d97 -[Tealium(Lifecycle) trackLifecycleEventForType:date:persistentData:dataSources:] + 157
	11  TealiumIOSLifecycle                 0x000000010ad93c9d -[Tealium(Lifecycle) executeLifecycleCommandForType:overrideDate:dataSources:autoTracked:] + 419
	12  TealiumIOSLifecycle                 0x000000010ad94079 -[Tealium(Lifecycle) enableLifecycleAutotracking] + 62
	13  TealiumIOS                          0x0000000109516a2d -[Tealium updateModules] + 134
	14  TealiumIOS                          0x000000010951645e -[Tealium refresh] + 27
	15  TealiumIOS                          0x00000001095164bd -[Tealium enable] + 76
	16  TealiumIOS                          0x0000000109516203 -[Tealium finalizeWithConfiguration:completion:] + 1473
	17  TealiumIOS                          0x000000010951551b __80+[Tealium instanceWithConfiguration:delegate:consentManagerDelegate:completion:]_block_invoke + 46
	18  libdispatch.dylib                   0x000000010ca9d595 _dispatch_call_block_and_release + 12
	19  libdispatch.dylib                   0x000000010ca9e602 _dispatch_client_callout + 8
	20  libdispatch.dylib                   0x000000010caa5b0b _dispatch_lane_serial_drain + 791
	21  libdispatch.dylib                   0x000000010caa6784 _dispatch_lane_invoke + 428
	22  libdispatch.dylib                   0x000000010cab089a _dispatch_workloop_worker_thread + 733
	23  libsystem_pthread.dylib             0x000000010ce8d61c _pthread_wqthread + 409
	24  libsystem_pthread.dylib             0x000000010ce8d415 start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by jonathanswong** [comment]
@f-gonzalez Sorry about that. We should have a fix out very shortly. If you remove TealiumIOSLifecycle, you can continue developing with our SDK or revert to 5.4.5 where that new method was not introduced. Thanks.

**Comment by jonathanswong** [comment]
Hi @f-gonzalez . How are you installing Tealium into your app? Are you using Cocoapods or doing it manually? In your logs, I see Tealium iOS Version 5.4.6 being used, but the crash says it fails on `initWithSafeLocale` which wasn't introduced until 5.4.7. Is it possible you are using different versions of TeailumIOS and TealiumIOSLifecycle? Thanks.

**Comment by f-gonzalez** [comment]
HI @jonwong-tealium , thanks the quick response and for pointing that out, yes I had different versions of the main SDK & lifeCycle. I have just changed that and set both to be 5.4.6 and with this version it's not crashing (but you should you probably check/review the 5.4.7). Thanks!
