### ISSUE TITLE
podspec not updated to latest version

### ISSUE THREAD

**Issue by roelspruit** [Tealium/tealium-ios#94]
Hi,

Thanks for the latest release of this library. It helps us a lot. I noticed that the podspec file was not updated for version 5.4.8 yet. Can this be fixed?

**Comment by craigrouse** [comment]
@roelspruit Sorry about that. We'll get it up ASAP!

**Comment by craigrouse** [comment]
@roelspruit the podspec may not be updated on the repo, but the pod is in fact released on CocoaPods: https://cocoapods.org/pods/TealiumIOS

We will update the podspec shortly, but this shouldn't stop you from updating the pod in your project.

**Comment by roelspruit** [comment]
ah my bad. Cocoapods didn't want to pick up version 5.4.8 but I just needed to run pod update. The un-changed podspec file on github sent me in the wrong direction. Thanks!

Roel
