### ISSUE TITLE
Getting audience names from visitorprofile

### ISSUE THREAD

**Issue by roelspruit** [Tealium/tealium-ios#95]
Hey, it's me again

We are trying to do something very specific on iOS. For the current user's TEALVisitorProfile. We want to know the names of the audiences the user belongs to. Thanks to the latest release of the library, we are able to call fetchVisitorProfile to get the user's profile. This profile has a function audiences() that should return a list of "TEALVisitorProfileAudienceAttribute". However, this type is unknown outside the tealium-ios framework. Instead it appears to return a list of Any. This means we are unable to read the contents of these attributes.

Additionally, I noticed that the audiences in the profile only get filled after a while. If I request the profile directly after I initialise the tealium SDK, most of the properties of the profile are null. If I do a call a bit later, the audiences ARE filled. The problem is I have no way of knowing when this happens. Is it possible to introduce a callback in the SDK that informs me whenever the profile is updated? instead of having to poll for it?

Looking forward to your reply!

Roel

**Comment by craigrouse** [comment]
@roelspruit it might be best to give you some direct support on this. Could you possibly email me? My email is pretty easy to guess. I'm interested to see what you're trying to do. Hope this works for you.

**Comment by jonwong-tealium** [comment]
@roelspruit For the first part of your question, when you make a fetch request, in the completion handler it returns a `(TEALVisitorProfile?, Error?)`. So you can do something like this:
```
        TealiumTracker.shared.tealium.fetchVisitorProfile { visitorProfile, error in
            print("visitorProfile: \(visitorProfile)")
            print("error: \(error)")
            print("audiences: \(visitorProfile?.audiences())")
            print("visitor profile: \(visitorProfile?.badges())")
        }
```
Does that help? Let me know if that's not clear. Thanks.

**Comment by jonathanswong** [comment]
Hi @roelspruit , thank you for bringing this to our attention. We'll make sure to expose these attributes in the next update coming out soon. In the meantime, you can use `rawProfile` to see the JSON representation of the `TEALVisitorProfile` object.

**Comment by roelspruit** [comment]
hi @jonwong-tealium thanks for the tip to use the rawProfile. I didn't try that route yet. Unfortunately it seems this rawProfile remains null. Even when the TEALVisitorProfile contains the visitorId and a list of audiences (that I cannot access)

**Comment by jonathanswong** [comment]
Hi @roelspruit . Check out release 5.4.9 that was just released. Those attributes are now public. Let us know if there's something else you need. Thanks.
